#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 0698adb
#
Name     : OpenSC
Version  : 0.26.1
Release  : 5
URL      : https://github.com/OpenSC/OpenSC/releases/download/0.26.1/opensc-0.26.1.tar.gz
Source0  : https://github.com/OpenSC/OpenSC/releases/download/0.26.1/opensc-0.26.1.tar.gz
Summary  : OpenSC PKCS#11 module
Group    : Development/Tools
License  : LGPL-2.1 MIT
Requires: OpenSC-bin = %{version}-%{release}
Requires: OpenSC-data = %{version}-%{release}
Requires: OpenSC-lib = %{version}-%{release}
Requires: OpenSC-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libeac)
BuildRequires : pkgconfig(libopenct)
BuildRequires : pkgconfig(libpcsclite)
BuildRequires : readline-dev
BuildRequires : sed
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# OpenSC documentation
Manual pages for the
[OpenSC command line tools](https://htmlpreview.github.io/?https://github.com/OpenSC/OpenSC/blob/master/doc/tools/tools.html)
as well as for the
[OpenSC configuration files](https://htmlpreview.github.io/?https://github.com/OpenSC/OpenSC/blob/master/doc/files/files.html)
are available online and typically distributed along with your installation.

%package bin
Summary: bin components for the OpenSC package.
Group: Binaries
Requires: OpenSC-data = %{version}-%{release}
Requires: OpenSC-license = %{version}-%{release}

%description bin
bin components for the OpenSC package.


%package data
Summary: data components for the OpenSC package.
Group: Data

%description data
data components for the OpenSC package.


%package dev
Summary: dev components for the OpenSC package.
Group: Development
Requires: OpenSC-lib = %{version}-%{release}
Requires: OpenSC-bin = %{version}-%{release}
Requires: OpenSC-data = %{version}-%{release}
Provides: OpenSC-devel = %{version}-%{release}
Requires: OpenSC = %{version}-%{release}

%description dev
dev components for the OpenSC package.


%package doc
Summary: doc components for the OpenSC package.
Group: Documentation

%description doc
doc components for the OpenSC package.


%package lib
Summary: lib components for the OpenSC package.
Group: Libraries
Requires: OpenSC-data = %{version}-%{release}
Requires: OpenSC-license = %{version}-%{release}

%description lib
lib components for the OpenSC package.


%package license
Summary: license components for the OpenSC package.
Group: Default

%description license
license components for the OpenSC package.


%prep
%setup -q -n opensc-0.26.1
cd %{_builddir}/opensc-0.26.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736893767
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736893767
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenSC
cp %{_builddir}/opensc-%{version}/COPYING %{buildroot}/usr/share/package-licenses/OpenSC/d1dd9b27a6a8d429ac99b8aed5c22516b4933a96 || :
cp %{_builddir}/opensc-%{version}/src/common/LICENSE.compat_getopt %{buildroot}/usr/share/package-licenses/OpenSC/7a85763803299a5978c266caa0ee3da546ba8a46 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cardos-tool
/usr/bin/cryptoflex-tool
/usr/bin/dnie-tool
/usr/bin/dtrust-tool
/usr/bin/egk-tool
/usr/bin/eidenv
/usr/bin/gids-tool
/usr/bin/goid-tool
/usr/bin/iasecc-tool
/usr/bin/netkey-tool
/usr/bin/npa-tool
/usr/bin/openpgp-tool
/usr/bin/opensc-asn1
/usr/bin/opensc-explorer
/usr/bin/opensc-notify
/usr/bin/opensc-tool
/usr/bin/piv-tool
/usr/bin/pkcs11-register
/usr/bin/pkcs11-tool
/usr/bin/pkcs15-crypt
/usr/bin/pkcs15-init
/usr/bin/pkcs15-tool
/usr/bin/sc-hsm-tool
/usr/bin/westcos-tool

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.opensc.notify.desktop
/usr/share/bash-completion/completions/cardos-tool
/usr/share/bash-completion/completions/cryptoflex-tool
/usr/share/bash-completion/completions/dnie-tool
/usr/share/bash-completion/completions/dtrust-tool
/usr/share/bash-completion/completions/egk-tool
/usr/share/bash-completion/completions/eidenv
/usr/share/bash-completion/completions/gids-tool
/usr/share/bash-completion/completions/goid-tool
/usr/share/bash-completion/completions/iasecc-tool
/usr/share/bash-completion/completions/netkey-tool
/usr/share/bash-completion/completions/npa-tool
/usr/share/bash-completion/completions/openpgp-tool
/usr/share/bash-completion/completions/opensc-asn1
/usr/share/bash-completion/completions/opensc-explorer
/usr/share/bash-completion/completions/opensc-notify
/usr/share/bash-completion/completions/opensc-tool
/usr/share/bash-completion/completions/piv-tool
/usr/share/bash-completion/completions/pkcs11-register
/usr/share/bash-completion/completions/pkcs11-tool
/usr/share/bash-completion/completions/pkcs15-crypt
/usr/share/bash-completion/completions/pkcs15-init
/usr/share/bash-completion/completions/pkcs15-tool
/usr/share/bash-completion/completions/sc-hsm-tool
/usr/share/bash-completion/completions/westcos-tool
/usr/share/opensc/asepcos.profile
/usr/share/opensc/authentic.profile
/usr/share/opensc/cardos.profile
/usr/share/opensc/cyberflex.profile
/usr/share/opensc/entersafe.profile
/usr/share/opensc/epass2003.profile
/usr/share/opensc/flex.profile
/usr/share/opensc/gids.profile
/usr/share/opensc/ias_adele_admin1.profile
/usr/share/opensc/ias_adele_admin2.profile
/usr/share/opensc/ias_adele_common.profile
/usr/share/opensc/iasecc.profile
/usr/share/opensc/iasecc_admin_eid.profile
/usr/share/opensc/iasecc_generic_oberthur.profile
/usr/share/opensc/iasecc_generic_pki.profile
/usr/share/opensc/isoApplet.profile
/usr/share/opensc/muscle.profile
/usr/share/opensc/myeid.profile
/usr/share/opensc/oberthur.profile
/usr/share/opensc/openpgp.profile
/usr/share/opensc/pkcs15.profile
/usr/share/opensc/rutoken.profile
/usr/share/opensc/rutoken_ecp.profile
/usr/share/opensc/rutoken_lite.profile
/usr/share/opensc/sc-hsm.profile
/usr/share/opensc/setcos.profile
/usr/share/opensc/starcos.profile

%files dev
%defattr(-,root,root,-)
/usr/lib64/libopensc.so
/usr/lib64/libsmm-local.so
/usr/lib64/pkgconfig/opensc-pkcs11.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/opensc/NEWS
/usr/share/doc/opensc/opensc.conf

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopensc.so.12
/usr/lib64/libopensc.so.12.0.2
/usr/lib64/libsmm-local.so.12
/usr/lib64/libsmm-local.so.12.0.2
/usr/lib64/onepin-opensc-pkcs11.so
/usr/lib64/opensc-pkcs11.so
/usr/lib64/pkcs11-spy.so
/usr/lib64/pkcs11/onepin-opensc-pkcs11.so
/usr/lib64/pkcs11/opensc-pkcs11.so
/usr/lib64/pkcs11/pkcs11-spy.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenSC/7a85763803299a5978c266caa0ee3da546ba8a46
/usr/share/package-licenses/OpenSC/d1dd9b27a6a8d429ac99b8aed5c22516b4933a96
